### ISSUE TITLE
[3ds] 1.9.9 crash

### ISSUE THREAD

**Issue by lencil** [libretro/mame2000-libretro#92]
changed to 1.8.9 core, work fine.

**Comment by mahoneyt944** [comment]
#98 should fix this once merged.

**Comment by lencil** [comment]
tried some games with 1.10.3，some game work fine, but some game like TMNT  still crash.
